export const productsArray = [
  {
    id: 1,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 2,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 3,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 4,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 5,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 6,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 7,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 8,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 9,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 10,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 11,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 12,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 13,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 14,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 15,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 16,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 17,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 18,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 19,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 20,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 21,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 22,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 23,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 24,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 25,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 26,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 27,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 28,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 29,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 30,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 31,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 32,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 33,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 34,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 35,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 36,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 37,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 38,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 39,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 40,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 41,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 42,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 43,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 44,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 45,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 46,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 47,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 48,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
  {
    id: 49,
    title: "Hermosa Soft",
    category: "PRODUCT CATEGORY",
    imageUrl: "/images/hermosa-soft.png",
  },
];
